---
title: "Week 1 ART of DS"
output: html_document
---

**I.	Data Analysis is Art**

Наука - это знание, которое мы понимаем так хорошо, что можем научить ему компьютер. Все остальное - это искусство.  
                                © Donald Knuth. Computer programming as an Art.1974.

Анализ данных - это искусство. В распоряжении аналитиков есть множество инструментов, таких как, например, линейная регрессия, и им нужно найти способ оценить все эти средства и применить их к данным, чтобы ответить на интересующий людей вопрос. Здесь требуется определенная доля креативности, которую тяжело объяснить, так же как и тяжело описать мысленный процесс, который ведет к успешному анализу данных.

Однако существуют определенные процедуры, которые приводят к хорошим результатам, о них мы и поговорим!



**II.	Epicycles of Analysis**

Анализ данных это интерактивный и нелинейный процесс, который лучше всего можно отразить в серии эпициклов, где каждый шаг помогает получить новую информацию и дает понять как усовершенствовать результаты уже проделанной работы.

ЗДЕСЬ КАРТИНКА СО СТР 5

В процессе анализа данных выделяется 5 ключевых шагов:

1. Постановка и усовершенствование исследовательского вопроса

2. Эксплораторный анализ данных

3. Построение статистических моделей

4. Интерпретация результатов

5. Презентация результатов

**III. Внутри каждого из пяти ключевых шагов важно следовать следующим этапам:**

1. Формулировка ожиданий, либо с помощью знаний, которыми исследователь уже обладает, или с использованием внешней информации,

2. Сбор информации (данных), сравнение данных с вашими ожиданиями и, если ожидания с ними не совпадают,

3. Пересмотр ожиданий или исправление данных таким образом, чтобы они совпадали.

Если ваши ожидания не совпадают с данными, то либо неверны ожидания, либо при проверке была допущена ошибка.

Еще раз проясним, формулировка ожиданий - это процесс сознательного размышления о том, какие результаты вы ждете прежде чем начнете совершать какие-либо действия, такие как изучение данных или написание команд.

Повторение этого 3-х фазного процесса называется "эпицикл анализа данных". Во время прохождения каждого этапа анализа данных также нужно проходить через эпицикл для того чтобы совершенствовать вопрос, эксплораторный анализ, модели, интерпретацию и презентацию результатов.

**IV. Соедините шаг эпицикла и его результат для первого этапа исследования "Постановка исследовательского вопроса".** Каковы ваши ожидания? Как вы будете собирать данные? Как усовершенствуются ожидания? После выполнения задания прочитайте пример исследования для лучшего понимания.

***Пример: Распространенность астмы в США***

Предположим, что ваш изначальный вопрос заключается в определении распространенности астмы среди взрослых, так как ваша компания хочет понять размеры рынка для нового препарата для лечения астмы.

На первом этапе усовершенствования вопроса, прежде всего, нужно сформулировать ожидания к вопросу, затем собрать информацию о нем и определить соответствует ли собранная информация вашим ожиданиям, и если нет, вам нужно будет пересмотреть вопрос. Ожидания заключаются в том, что ответ на вопрос неизвестен и что он может быть получен. Однако, литературный и интернет обзор показал, что этот вопрос уже был исследован, и ответ на него постоянно дополняется Центром борьбы с заболеваниями, поэтому вы пересматриваете вопрос с тем фактом, что вы можете просто зайти на сайт Центра, чтобы получить информацию о распространенности астмы. 

Вы информируете об этом начальника. В ходе обсуждения выясняется, что новый препарат от астмы таргетирует людей, у которых астма не контролируется медикаментами, доступными в настоящее время. Таким образом, вы выявляете более хороший вопрос "Как много людей в США страдают от астмы, которая в настоящее время не контролируется, и каковы демографические предикторы неконтролируемой астмы?" Далее вы повторяете процесс сбора информации, чтобы определить можно ли ответить на вопрос и хорош ли он, продолжая до тех пор, пока не будете уверены в том, что усовершенствовали вопрос до такой степени, что на него можно ответить с имеющимися данными.

*Задание:*

Вопрос интересен аудитории - Постановка ожиданий 

Литературный обзор/Эксперты - Сбор информации

Уточнение вопроса - Пересмотр ожиданий

**V. Сделайте то же самое для этапа "Эксплораторный анализ данных"**

***Пример: Распространенность астмы в США***

Предположим, что вы нашли базу данных, которую можно загрузить с сайта и которая содержит выборку, репрезентующую взрослое население США, 18 лет и старше. Следующим этапом вы проводите эксплораторный анализ и начинаете с ожидания того, что когда вы будете исследовать ваши данные, они будут содержать 10 123 строки, каждая из которых будет отражать индивида из США, так как такую информацию предоставляет документация, которая прилагается к базе. Там же указано, что в данных будет переменная, указывающая возраст индивида. 

Однако когда вы начинаете исследовать данные, то обнаруживаете, что в базе всего 4 803 строки, поэтому вы возвращаетесь к документации, чтобы подтвердить верность ваших ожиданий о количестве строк, сделав это, вы возвращаетесь на сайт и обнаруживаете, что там два файла с нужными вам данными, первый состоит из 4 803 строк и второй, содержащий недостающие 5 320. Вы загружаете второй файл и соединяете его с первым. 

Теперь, когда у вас правильное количество строк, вы двигаетесь дальше и определяете соответствуют ли ваши ожидания возрасту выборки, где каждому должно быть 18 лет и больше. Вы делаете summarize для переменной возраст, смотрите минимальные и максимальные значения и находите, что все индивиды 18-ти лет и старше, что соответствует вашим ожиданиям. Хотя существует еще много вещей, которые можно было бы сделать для исследования данных, эти две процедуры являются примерами подхода. В конечном итоге, вы приходите к тому, что данные годятся для оценки распространенности неконтролируемой астмы среди взрослых в США.

*Задание:*

Данные подходящие для вопроса - Постановка ожиданий 

Построение описательных графиков данных - Сбор информации

Усовершенствование вопроса или сбор дополнительных данных - Пересмотр ожиданий

**VI. Как вы примените эпицикл при построении статистических моделей?** Выполните задание, затем прочитайте текст ниже
  
***Пример: Распространенность астмы в США***

Третий этап - построение статистических моделей необходим для определения демографических характеристик, которые лучше всего предсказывают, что кто-то страдает неконтролируемой астмой. Статистические модели помогают точно сформулировать вопрос, таким образом что вы видите как вы хотите использовать данные: посчитать ли определенный параметр или сделать предсказание. Статистические модели также представляют формальную рамку, в которой вы можете проверять свои выводы и тестировать предположения. 

После этого этапа, вы оценили распространение неконтролируемой астмы среди взрослых в США и определили, что возраст, пол, раса, индекс массы тела, статус курения, и доход являются лучшими из имеющихся предикторов неконтролируемой астмы. Далее вы переходите к четвертому этапу, интерпретации результатов. На практике, интерпретация результатов происходит вместе с построением моделей, но концептуально это два разных процесса.

*Задание:*

Первичная модель отвечает на вопрос - Постановка ожиданий

Построение вторичных моделей, анализ чувствительности - Сбор информации

Усовершенствование модели путем добавление новых предикторов - Пересмотр ожиданий

**VII. Четвертый этап - интерпретация результатов.** Какие ожидания будут на этом этапе? Как сбор информации и пересмотр ожиданий могут быть проделаны? Выполните задание, а затем прочтите текст примера

***Пример: Распространенность астмы в США***

Предположим, вы построили финальную модель и теперь переходите к интерпретации выводов модели. Когда вы исследуете модель, вашими изначальными ожиданиями является, что возраст, афроамериканская/черная раса, индекс массы тела, статус курения, и маленький доход позитивно ассоциируются с неконтролируемой астмой. 

Однако, вы замечаете, что женщины негативно связаны с неконтролируемой астмой, хотя обсуждение с экспертами говорит о том, что среди взрослых, женский пол должен быть позитивно связан с неконтролируемой астмой. Это несоответствие между ожиданиями и результатами вынуждает вас сделать паузу и провести некоторое исследование, чтобы определить, действительно ли правильны ваши результаты, и нужно ли приспособить свои ожидания или если есть проблема с результатами, а не ожиданиями. После исследования вы обнаруживаете, что думали, что гендерная переменная была закодирована 1 для женщины и 0 для мужчины, но вместо этого документация указывает, что гендерная переменная была закодирована 1 для мужчины и 0 для женщины. Таким образом, интерпретация ваших результатов была неправильной, не ваши ожидания. Теперь, когда вы понимаете кодирование для гендерной переменной, ваша интерпретация выводов модели соответствует вашим ожиданиям, таким образом, вы можете идти дальше к презентации ваших результатов.

*Задание:*

Интерпретация анализа предоставляет определенный & значимый ответ на вопрос - Постановка ожиданий   

Интерпретируйте весь анализ с вниманием на размеры эффекта & неопределенность - Сбор информации

Пересмотр EDA и/или модели, чтобы предоставить определенный & поддающийся толкованию ответ - Пересмотр ожиданий

**VIII. На финальном этапе анализа вам нужно рассказать о его результатах.** Выполните задание и прочитайте текст ниже

***Пример: Распространенность астмы в США***

Наконец, вы рассказываете о своих выводах, и опять применяете эпицикл. Будем считать, что вы подготовили неформальный отчет. Ваши ожидания состоят в том, что он интересен вашему начальнику. Вы встречаетесь со своим боссом, чтобы обсудить результаты, и она задает два вопроса: (1)как давно данные были собраны и (2)какие изменения демографических паттернов, произойдут за следующие 5-10 лет, которые повлияют на распространение неконтролируемой астмы. Несмотря на то, что может быть разочаровывающе, что ваш отчет не полностью удовлетворяет потребности начальника, получение фидбэка является важнейшей частью выполнения анализа данных, и на самом деле, мы утверждаем, что хороший анализ данных требует презентации результатов, обратной связи, и затем действий в ответ на обратную связь.

Несмотря на то, что вы знаете ответ о годах, когда данные были собраны, вы понимаете, что не включали эту информацию в свой отчет, таким образом, вы пересматриваете отчет и дополняете его. Также вы понимаете, что вопрос босса о влиянии меняющихся демографических паттернов на распространение неконтролируемой астмы - хороший, так как ваша компания хочет предсказать размер рынка в будущем, таким образом, вы теперь можете провести новый анализ. Вы должны также чувствовать пользу, которую принес отчет, так как он выдвинул дополнительные вопросы на первый план, а это - одна из характеристик успешного анализа данных.

*Задание:*

Процесс & анализ поняты, полны & значимы для аудитории - Постановка ожиданий

Поиск фидбэка - Сбор информации

Пересмотр исследования или переход к его презентации - Пересмотр ожиданий

**IX. Прежде чем проводить исследование вам нужно понять тип вопроса, на который вы отвечаете**

**Существуют шесть типов вопросов:**

***1. Descriptive***

Вопрос, нацеленный на обобщение особенностей ряда данных (пропорция мужчин, среднее количество порций свежих фруктов и овощей в день). Нет никакой интерпретации самого результата, так как результат - это факт, признак набора данных, с которыми вы работаете.

***2. Exploratory***

Вопрос, в котором вы анализируете данные, чтобы определить, есть ли тенденции или отношения между переменными. Такой тип анализа также называют “гипотеза-создающие” исследования, потому что вы ищете паттерны, которые поддержали бы предлагаемую гипотезу. Если у вас есть идея, что диета так или иначе связана с вирусными инфекциями, вы могли бы исследовать эту идею, проанализировав отношения между набором диетических факторов и вирусными болезнями. Предположим, в результате анализа вы обнаружили, что люди, которые следовали диете с высоким содержанием определенных продуктов, меньше заболевали вирусными инфекциями, чем те, диета которых не была обогащена этими продуктами. Таким образом, вы предлагаете гипотезу, что среди взрослых, съедающих по крайней мере 5 порций свежих овощей и фруктов в день меньшее количество заболевают вирусными инфекциями в год.

***3. Inferential***

В этом типе вопроса вы переформулируете предложенную гипотезу в виде вопроса и отвечаете на него, анализируя новый набор данных, который на нашем примере будет репрезентативной выборкой взрослых в США. Анализируя этот набор данных вы определяете, сохраняется ли тенденция, выявленная вами при проведении эксплораторного анализа на новом наборе данных, репрезентующих генеральную совокупность. Другими словами, с помощью этого анализа, вы будете в состоянии определить, что верно, в среднем, для взрослого населения в США. 

***4. Predictive***

Используя predictive question вы бы спрашивали, какой тип людей будет придерживаться диете, содержащей большое количество свежих фруктов и овощей в течение следующего года. В этом типе вопроса вы меньше интересуетесь тем, что заставляет кого-то придерживаться определенной диеты, чем тем, что предсказывает, будет ли кто-то придерживаться этой определенной диете.
Например, более высокий доход может быть одним из важнейших предсказателей, и вы не можете знать (или даже озадачиваться тем), почему люди с более высоким доходом вероятнее будут придерживаться диете с высоким содержанием свежих овощей и фруктов, самым важным для вас будет то, что доход - фактор, который предсказывает это поведение.

Хотя inferential question может сказать нам, что люди, которые едят определенный тип продуктов, склонны иметь меньше вирусных болезней, ответ на этот вопрос не говорит нам, что употребление в пищу этих продуктов вызывает сокращение количества вирусных болезней. Такой ответ будет получен при causal question.

***5. Causal***

Целью этого вопроса является определение, изменится ли один фактор при изменении другого фактора, в среднем, в генеральной совокупности.

***6. Mechanistic***

Наконец, ни один из вопросов, описанных до сих пор, не приведет к ответу, который скажет нам, что если действительно диета вызывает сокращение количества вирусных болезней, как диета приводит к сокращению количества вирусных болезней. Вопрос, который спрашивает, как диета с высоким содержанием свежих фруктов и овощей приводит к сокращению количества вирусных болезней, называется mechanistic question.

Во многих случаях, при проведении анализа исследователю необходимо дать ответы сразу на несколько типов вопросов. Например, если исследователь при ?анализе данных стремится ответить на inferential question, то для достижения этой цели также потребуется дать ответ на descriptive и exploratory questions . Также тип вопроса, который вы задаете, частично определяется доступными вам данными (если только вы не планируете провести исследование и собрать данные для анализа)

Более подробное обсуждение вы можете найти в статье, опубликованной в Science by Roger and Jeff Leek здесь http://www.sciencemag.org/content/347/6228/1314.short

**X. Соедините тип исследовательского вопроса и его определение:**

Descriptive - описывает характеристики набора данных

Exploratory - выявляет возможные паттерны, тренды или отношения между переменными, помогает формулировать гипотезы 

Inferential - проверяет верна ли гипотеза на основе данных выборки

Predictive - прогнозирует те случаи, которые еще не произошли

Causal - выясняет изменится ли один фактор, если изменится второй

Mechanistic - объясняет почему меняется один показатель, в зависимости от другого

**XI. Существует пять характеристик хорошего вопроса для анализа данных:**

- вопрос должен быть интересен аудитории

- вопрос не должен быть уже отвеченным  

Исследование и обсуждение с экспертами может быть полезно, потому что даже если на ваш конкретный вопрос ответа еще не было дано, могут быть ответы на связанные с ним вопросы и эти ответы могут быть информативными для принятия решения продолжить ли использовать ваш вопрос.

- вопрос должен быть правдоподобным 

Если вы задаете неправдоподобный вопрос, то скорее всего окажетесь в ситуации когда ответ трудно интерпретировать или быть уверенным в нем

- вопрос должен быть "отвечаемым"

На некоторые замечательные вопросы невозможно ответить - либо из-за отсутствия данных или инструментов для их сбора, либо этических проблем.

- вопрос должен быть конкретным

**Сравните:**

"Полезней ли для здоровья правильное питание?" 
"Ведет ли употребление в пищу минимум 5-ти порций свежих овощей и фруктов в день к уменьшению количества случаев заболеваемости ОРВИ?"

**XII. Следующий вопрос правдоподобен:**

"Коррелируют ли продажи пепперони с продажами йогурта?" - False

**XIII. Следующий вопрос правдоподобен:**

"Верно ли, что продажи пепперони увеличиваются, когда они разложены в магазине рядом с соусом для пиццы, а не с другой расфасованной едой?" - True

**XIV. Следующий вопрос конкретен:**

"Верно ли, что мужчины, в среднем, работают больше часов в неделю на основной работе, чем женщины?" - True







