---
title: "Dplyr"
output: html_document
---

###Шаг 1 
На предыдущей неделе вы уже познакомились с одним из пакетов для визуализации данных ггплот
Данный модуль нацелен на то, чтобы познакомить вас с аггрегацией данных. 
Что такое агрегация

Мы будем использовать основные пакеты входящие в tidyverse: dplyr  
Шпаргалку можно найти здесь:  https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

```{r}
library(tidyverse)
#library(dplyr)
#library(tidyr)
```


###Шаг 2 Соедините функции из пакета dplyr с их описанием:? это переделать 

3 Для соединения данных их разных таблиц применяется операция join. Соединяя при помощи этой операции таблицы, мы получаем в качестве результата таблицу в которой часть столбцов взята из первой таблицы, а часть столбцов из второй таблицы.

Какую функцию из пакета dplyr нужно использовать, если мы хотим левую таблицу a сделать более приоритетной, то есть включать ее строки в результат, даже если для них нет соответствия в правой таблице b:

 cbind(a, b)
 left_join(a, b, by = "x1")
 right_join(a, b, by = "x1")
 anti_join(a, b, by = "x1")


4 Для более последовательного представления кода можно использовать "пайпы" или %>% из пакета dplyr, при помощи которых можно отправить результат выполнения одной команды в следующую.

Оператор %>% в RStudio вызывается сочетанием клавиш Ctrl + Shift + m. 

Продолжим работу с датасетом diamonds. Посчитайте средние значения по переменным price и carat для каждой группы переменной cut.

5 Используя код из предыдущего задания, посчитайте сколько карат в среднем весит бриллиант из группы Fair: 

6 Рассмотрим таблицу diamonds, содержащую информацию  о ценах и прочих характеристиках бриллиантов.

> ?diamonds
> d = as.data.frame(diamonds)
> head(d)

Применив функцию select(), оставьте в таблице d столбцы: carat, cut  и price. Дополнительно оставьте все значения удовлетворяющие условию carat > 0.5.  

В результате должна получиться таблица вида: 

7 Из данных msleep оставьте строки, содержащие информацию только о домашних животных (domesticated). Для этих данных создайте новую колонку brain_body, в которой будет указано соотношение массы мозга к массе тела животного. 

Упорядочьте значения в таблице по убыванию по новой переменной.

?msleep

8 У какого одомашненного животного в таблицу msleep наибольшее соотношение массы мозга и массы тела? 

9 Рассмотрим еще один набор данных, содержащий информацию о приеме в Беркли в 1973 году

> d <- as.data.frame(UCBAdmissions)
> head(d)
     Admit Gender Dept Freq
1 Admitted   Male    A  512
2 Rejected   Male    A  313
3 Admitted Female    A   89
4 Rejected Female    A   19
5 Admitted   Male    B  353
6 Rejected   Male    B  207
Предположим, мы хотим проверить, имела ли место половая дискриминация при приеме студентов в Беркли вне зависимости от подразделения (dept).

Сгруппируйте данные, воспользовавшись функциями из пакета dplyr, а затем постройте столбчатую диаграмму, на которой можно сравнить количество поступивших и не поступивших студентов в зависимости от пола.

Подсказка: для того, чтобы отразить три переменных на графике, воспользуйтесь аргументом fill.
