
##Шаг 1: "Теория: функции и аргументы для построения графиков"

> “The simple graph has brought more information to the data analyst’s mind than any other device.” — John Tukey

**ggplot2** является одним из наиболее распространенных и гибких пакетов для построения любых типов графиков, способных наилучшим образом показать существующие взаимосвязи в исследуемых данных.

Любой график из пакета **ggplot2** строится слоями, где каждый новый слой добавляется при помощи оператора '+', общая формула для построения любого графика может быть представлена следующим образом:

```{r, eval=FALSE, include=T}
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <COORDINATE_FUNCTION> +
  <FACET_FUNCTION>
```

*Она может быть дополнена большим количеством дополнительных слоев и эстетик.*
  
Основные функции для построения графиков разных типов (*вместо < GEOM_FUNCTION >*):

* **geom_histogram()** - гистограмма
* **geom_bar()** - столбчатая диаграмма
* **geom_boxplot()** - ящик с усами
* **geom_point()** - диаграмма рассеяния
* **geom_vline()** - линия 

Для добавления переменных из рассматриваемого датасета на график необходимо присвоить их отдельно для оси X и оси Y в функции aes вместо *< MAPPINGS >*.

После присваивания переменных можно также изменить внешний вид графика, добавляя дополнительные аргументы в функцию графика. В данном уроке будут рассмотрены следующие компоненты:

* **alpha** - прозрачность геометрических объектов на графике
* **color** - цвет границ геометрических объектов на графике
* **fill** - цвет заливки геометрических объектов на графике
* **linetype** - цвет линии, добавленной на график
* **shape** - форма геометрических объектов на графике
* **size** - размер геометрических объектов на графике
* **stat** - статистические преобразования (сглаживание, разделение на промежутки и т.д.) 
* **position** - определяет, как расположить геометрические объекты на графике

Также будут рассмотрены дополнительные функции, добавляемые отдельными слоями, для изменения реперзентации графиков:

* **coord_flip()** - меняет местами расположение осей
* **facet_grid()** - посзволяет визуализировать несколько графиков сразу
* **scale_fill_brewer()** - применяет палитры для графиков с дополнительной группирующей переменной, добавленной через аргумент *fill*

## Шаг 2: "Теория + задание: типы переменных и виды графиков"

Каждый график включает в себя как минимум одну переменную из рассматриваемого датасета, поэтому перед тем, как начать его построение необходимо определить, к какому типу относятся все используемые переменные.


Каждый отдельный вид графика может в лучшей степени репрезентировать переменные определенных типов. 
